#Application URL
url = https://opensource-demo.orangehrmlive.com/

#Browser Configuration --- From TestNG file


#Run browser in headless mode
headless = true

#Credentials
username = admin
password = admin123

#ImplicitWait (in seconds)
implicitWait = 30

#ExplicitWait
explicitWait = 30